version: "3.3"

services: 
  node: 
    image: node
    restart: always
    container_name: node
    working_dir: /home/node/app
    volumes: 
      - ./:/home/node/app
    ports: 
      - 80:80
    # command: "npm install mongoose --save"
    command: "npm start"

  mongo:
    image: mongo
    restart: always
    container_name: mongo