version: "3"

services: 
  node: 
    image: node
    container_name: node
    working_dir: /home/node/app
    volumes: 
      - ./:/home/node/app
    ports: 
      - 80:80
    # command: "npm install express ejs request --save"
    command: "npm start"