version: "3.3"

services:
 
  mongo: 
    image: mongo
    restart: always
    container_name: mongodb
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: change_me