version: "3"
services: 
  node:
    image: node
    # user: node
    container_name: node
    working_dir: /home/node/app
    environment: 
      - NODE_ENV=development
    volumes: 
      - ./:/home/node/app
    ports: 
      - 3000:3000
    # Install required packages if necessary
    # command: "npm install express --save"
    command: "npm start"